version: '3'

services:
  node:
    build: ./docker/node
    container_name: "node"
    environment:
      - NODE_ENV:production
    volumes:
      - ~/yiniau-s-blog:/app
    ports:
      - 8090:8090
    command: npm run docker-compose-deploy