version: '3'

services:
  mongodb:
    image: mongo:3.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log
    volumes:
      - ~/db/mongo-data:/data/db
      - ~/db/mongo-log:/var/log
    networks:
      - defalut
      - app_net
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod --smallfiles --logpath /var/log/log.log --logappend --dbpath /data/db
  node-server:
    build: ./docker/node
    container_name: "node-server"
    environment:
      - NODE_ENV:production
    volumes:
      - ~/github/yiniau-s-blog:/app
      - ~/log/access.log:/log/access.log
    networks:
      - defalut
      - app_net
    links:
      - mongodb:db
    depends_on:
      - mongodb
    ports:
      - "8090:8090"
    command: npm run docker-compose-deploy
  node-client:
    build: ./docker/node
    container_name: "node-client"
    environment:
      - NODE_ENV:production
    volumes:
      - ~/github/yiniau-s-blog:/app
    networks:
      - defalut
      - app_net
    ports:
      - "5000:5000"
    command: npm run client-serve
  node-weixin:
    build: ./docker/node
    container_name: "node-weixin"
    environment:
      - NODE_ENV:production
    volumes:
      - ~/github/weixin-server:/app
      - ~/log/koa-weixin-access.log:/log/koa-weixin-access.log
    networks:
      - defalut
      - app_net
    ports:
      - "5001:8090"
    command: npm run weixin-server
  node-client-test:
    build: ./docker/node
    container_name: "node-client-test"
    environment:
      - NODE_ENV:production
    volumes:
      - ~/github/yiniau-s-blog/test-build:/app
    networks:
      - defalut
      - app_net
    ports:
      - "5002:5000"
    command: npm run client-test-server
networks:
  defalut:
  app_net:
    external: true
