version: '3'

services:
  node:
    build: ./docker/node
    container_name: "node"
    environment:
      - NODE_ENV:production
    volumes:
      - ~/github/yiniau-s-blog:/app
      - ~/log/access.log:/log/access.log
    external_links:
      - mongodb:db
    ports:
      - "8090:8090"
    command: npm run docker-compose-deploy